FROM amazoncorretto:21-alpine-jdk

# Install curl
RUN apk --no-cache add curl

WORKDIR /app

# Copy only the files needed for dependency resolution first
COPY gradlew .
COPY gradlew.bat .
COPY gradle ./gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradle.properties .

# Grant execution rights to the Gradle wrapper
RUN chmod +x ./gradlew

# (Optional but Recommended) Resolve dependencies to create a separate cache layer
# This step might need a command that only downloads dependencies without compiling.
# If your build is simple, you can skip this and go straight to building.
# A common way is to try to build an empty project or run a 'dependencies' task.
RUN ./gradlew build --no-daemon || true

# Copy the rest of the source code
COPY src ./src

# Build the application and create the distribution
# Combining these into one layer can be more efficient
RUN ./gradlew build installDist --no-daemon

# Set the port the application runs on
EXPOSE 8080

# Run the application using the script generated by installDist
# Replace 'your-project-name' with the actual name from your settings.gradle.kts
CMD ["/app/build/install/Auto-Opener/bin/Auto-Opener"]
